### ISSUE TITLE
I get an error for Blaze-Layout-component 

### ISSUE THREAD

**Issue by emehmet** [peerlibrary/blaze-layout-component#2]
Hi,
I'm get an error like below while I work on Blaze Layout Component.

> Exception in template helper: TypeError: this._renderRegion is not a function

```
class MainLayoutComponent extends BlazeComponent{
  renderHeader(parentComponent){
    this._renderRegion("header",parentComponent);
  }
  renderTopmenu(parentComponent){
    this._renderRegion("topmenu",parentComponent);
  }
  renderContent(parentComponent){
    this._renderRegion("content",parentComponent);
  }
}
```

Thank you for your replies

**Comment by mitar** [comment]
You should extend `BlazeLayoutComponent` and not `BlazeComponent`.

**Comment by emehmet** [comment]
Thank you for your reply!

Sorry I missed.

Now i'm get error like so.

> Exception in defer callback: Error: Expected template or null, found: undefined

**Comment by mitar** [comment]
This is not enough information to be able to help you in any meaningful way.

**Comment by emehmet** [comment]
I'm use FlowRouter. 

```
FlowRouter.route('/', {
  name: 'home',
  action: function (params, queryParams) {
    console.log("/");
    BlazeLayout.render('MainLayoutComponent', {
      header: 'HeaderComponent',
      topmenu: 'TopmenuComponent',
      content: 'DashboardComponent'
    });
  }
});
```

```
class HeaderComponent extends BlazeComponent {
  template() {
    return "HeaderComponent";
  }
}
HeaderComponent.register("HeaderComponent");
```

```
<template name="HeaderComponent">
  header
</template>
```

These are code which i use. And also MainLayoutComponent above.

**Comment by mitar** [comment]
I see I forget `return`s in the README. I updated the README.

**Comment by emehmet** [comment]
Ok. it's works. Many thanks.

**Comment by mitar** [comment]
Thanks for reporting.
