### ISSUE TITLE
What does _renderRegion do?

### ISSUE THREAD

**Issue by adrprado** [peerlibrary/blaze-layout-component#3]
In the README example, what's the `_renderRegion` purpose? And what about the `parentComponent`?

```
class ColumnsLayoutComponent extends BlazeLayoutComponent {
  renderFirst(parentComponent) {
    return this._renderRegion('first', parentComponent);
  }
}
```

**Comment by mitar** [comment]
`_renderRegion` is just a helper method which does all the heavy work for a particular region. The idea is that you define a method with the name you want to use in templates (`renderFirst`) and use `_renderRegion` to then really render the region in that place.

`parentComponent` is optional. By default it is automatically set to current component, which is probably parent you want.
