### ISSUE TITLE
Problems with using `useraccounts:flow-routing`

### ISSUE THREAD

**Issue by thebarty** [peerlibrary/blaze-layout-component#4]
Hi guys,

just ran into a problem when combining this with `useraccounts:flow-routing` (https://github.com/meteor-useraccounts/flow-routing) and I am getting the error:
```
 "Exception in template helper: Error: Unknown component 'fullPageAtForm'"
```

The error is thrown right here https://github.com/peerlibrary/blaze-layout-component/blob/085155cfb9b4294cc4a2dc416e11352477f9b9b3/layout.coffee#L46, probably because the `useraccounts:core` "{{>fullPageAtForm}}" is **NOT a BlazeComponent.**

This is my config
```
AccountsTemplates.configure({
  defaultLayout: 'LayoutComponent',  // BlazeLayoutComponent (`return this._renderRegion('content', parentComponent)`)
  defaultLayoutRegions: {},
  defaultContentRegion: 'content',
})

AccountsTemplates.configureRoute('signIn')
```

@mitar: Do you have a quick fix for this?

**Comment by mitar** [comment]
I am using flow-routing in this app: https://github.com/peer/mind/blob/master/packages/peermind/package.js#L40

And pass a component in: https://github.com/peer/mind/blob/master/packages/peermind/account/config.coffee#L31

So not sure exactly where your code is different.

**Comment by mitar** [comment]
This is my account form: https://github.com/peer/mind/blob/master/packages/peermind/account/form.html
